jtype: SRExecutor
py_modules:
  - __init__.py
metas:
  name: SRExecutor
  description: SwinIR for super resolution tasks.
  url: https://github.com/selmiss/excutor_SwinIR
  keywords: [SwinIR, vision, image, super-resolution, pytorch]